export const LANGUAGES = [
  // 🌍 全球最常用语言
  { label: 'EN', value: 'en' },
  { label: 'ZH-CN', value: 'zh-CN' },
  { label: 'ZH-TW', value: 'zh-TW' },
  { label: 'ES', value: 'es' },
  { label: 'FR', value: 'fr' },
  { label: 'DE', value: 'de' },
  { label: 'JA', value: 'ja' },
  { label: 'KO', value: 'ko' },
  { label: 'RU', value: 'ru' },
  { label: 'AR', value: 'ar' },
  { label: 'PT', value: 'pt' },
  { label: 'IT', value: 'it' },

  // 🌏 亚洲常见语言
  { label: 'HI', value: 'hi' },
  { label: 'BN', value: 'bn' },
  { label: 'UR', value: 'ur' },
  { label: 'TH', value: 'th' },
  { label: 'VI', value: 'vi' },
  { label: 'ID', value: 'id' },
  { label: 'MS', value: 'ms' },
  { label: 'TL', value: 'fil' },
  { label: 'TA', value: 'ta' },
  { label: 'TE', value: 'te' },
  { label: 'ML', value: 'ml' },
  { label: 'KN', value: 'kn' },
  { label: 'MR', value: 'mr' },
  { label: 'NE', value: 'ne' },
  { label: 'MY', value: 'my' },
  { label: 'SI', value: 'si' },

  // 🌍 欧洲语言
  { label: 'NL', value: 'nl' },
  { label: 'PL', value: 'pl' },
  { label: 'TR', value: 'tr' },
  { label: 'EL', value: 'el' },
  { label: 'SV', value: 'sv' },
  { label: 'DA', value: 'da' },
  { label: 'NO', value: 'no' },
  { label: 'FI', value: 'fi' },
  { label: 'HU', value: 'hu' },
  { label: 'CS', value: 'cs' },
  { label: 'SK', value: 'sk' },
  { label: 'SL', value: 'sl' },
  { label: 'HR', value: 'hr' },
  { label: 'SR', value: 'sr' },
  { label: 'RO', value: 'ro' },
  { label: 'BG', value: 'bg' },
  { label: 'UK', value: 'uk' },
  { label: 'LV', value: 'lv' },
  { label: 'LT', value: 'lt' },
  { label: 'ET', value: 'et' },

  // 🌍 中东与非洲
  { label: 'FA', value: 'fa' },
  { label: 'SW', value: 'sw' },
  { label: 'AF', value: 'af' },
  { label: 'HE', value: 'he' },

  // 🧭 其他较少使用的语言
  { label: 'CA', value: 'ca' },
  { label: 'GL', value: 'gl' },
  { label: 'IS', value: 'is' },
  { label: 'MK', value: 'mk' },
  { label: 'KA', value: 'ka' },
  { label: 'KK', value: 'kk' },
  { label: 'MN', value: 'mn' },
] as const
